// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddMonitoredFolder(arg1:string,arg2:string):Promise<domain.MonitoredFolder>;

export function BrowseFolder():Promise<string>;

export function DeleteMonitoredFolder(arg1:string):Promise<void>;

export function GetMonitoredFolders():Promise<Array<domain.MonitoredFolder>>;

export function ScanFolder(arg1:string):Promise<domain.ScanResult>;

export function UpdateMonitoredFolder(arg1:string,arg2:string,arg3:string):Promise<domain.MonitoredFolder>;
