// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function AddMonitoredFolder(arg1:string,arg2:string):Promise<services.MonitoredFolder>;

export function DeleteMonitoredFolder(arg1:string):Promise<void>;

export function GetMonitoredFolders():Promise<Array<services.MonitoredFolder>>;

export function ScanFolder(arg1:string):Promise<services.ScanResult>;

export function UpdateMonitoredFolder(arg1:string,arg2:string,arg3:string):Promise<services.MonitoredFolder>;
