// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMonitoredFolder(arg1, arg2) {
  return window['go']['main']['App']['AddMonitoredFolder'](arg1, arg2);
}

export function DeleteMonitoredFolder(arg1) {
  return window['go']['main']['App']['DeleteMonitoredFolder'](arg1);
}

export function GetMonitoredFolders() {
  return window['go']['main']['App']['GetMonitoredFolders']();
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function UpdateMonitoredFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateMonitoredFolder'](arg1, arg2, arg3);
}
